---
# day-0 applications playbook
# deploys essential cluster applications after k3s infrastructure is up:
# - longhorn: distributed storage
# - cert-manager: tls certificate automation
# - argocd: gitops continuous delivery
# 
# run this AFTER site.yml has successfully deployed the cluster

- name: verify cluster is accessible
  hosts: k3s_control_plane[0]
  gather_facts: false
  become: true
  tasks:
    - name: check if kubeconfig exists
      ansible.builtin.stat:
        path: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_check

    - name: fail if cluster not deployed
      ansible.builtin.fail:
        msg: "k3s cluster not found. run site.yml first."
      when: not kubeconfig_check.stat.exists

    - name: verify cluster is responding
      ansible.builtin.command:
        cmd: k3s kubectl get nodes
      register: nodes_check
      changed_when: false
      failed_when: nodes_check.rc != 0

- name: deploy longhorn storage
  hosts: k3s_control_plane[0]
  gather_facts: false
  become: true
  tasks:
    - name: include longhorn role
      ansible.builtin.import_role:
        name: longhorn

- name: deploy cert-manager
  hosts: k3s_control_plane[0]
  gather_facts: false
  become: true
  tasks:
    - name: include cert_manager role
      ansible.builtin.import_role:
        name: cert_manager

- name: deploy argocd
  hosts: k3s_control_plane[0]
  gather_facts: false
  become: true
  tasks:
    - name: include argocd role
      ansible.builtin.import_role:
        name: argocd

- name: display access information
  hosts: k3s_control_plane[0]
  gather_facts: false
  become: true
  tasks:
    - name: get argocd initial password
      ansible.builtin.shell: |
        k3s kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
      register: argocd_password
      changed_when: false
      failed_when: false

    - name: display application status
      ansible.builtin.debug:
        msg:
          - "day-0 applications deployed successfully"
          - ""
          - "longhorn dashboard:"
          - "  kubectl port-forward -n longhorn-system svc/longhorn-frontend 8080:80"
          - "  then visit: http://localhost:8080"
          - ""
          - "argocd dashboard:"
          - "  kubectl port-forward -n argocd svc/argocd-server 8081:443"
          - "  then visit: https://localhost:8081"
          - "  username: admin"
          - "  password: {{ argocd_password.stdout }}"
          - ""
          - "cert-manager:"
          - "  kubectl get clusterissuers"
          - "  kubectl get certificates -A"